package com.juliaaano.solarvillage_kie;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Order implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String member;
	private java.lang.String address;
	private boolean hoa;

	private boolean approved;

	public Order() {
	}

	public Order(com.juliaaano.solarvillage.model.NewOrder newOrder) {
		this.member = newOrder.getMember();
		this.address = newOrder.getAddress();
		this.hoa = newOrder.isHoa();
	}
	
	public void approve() {
		this.approved = true;
	}

	public java.lang.String getMember() {
		return this.member;
	}

	public void setMember(java.lang.String member) {
		this.member = member;
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public boolean isHoa() {
		return this.hoa;
	}

	public void setHoa(boolean hoa) {
		this.hoa = hoa;
	}

	public boolean isApproved() {
		return this.approved;
	}

	public void setApproved(boolean approved) {
		this.approved = approved;
	}

	public Order(java.lang.String member, java.lang.String address,
			boolean hoa, boolean approved) {
		this.member = member;
		this.address = address;
		this.hoa = hoa;
		this.approved = approved;
	}

}